AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create 1 master EC2 and worker Auto Scaling Group with SSM Session Manager
  and CloudWatch Agent installed and running after reboot.

Parameters:
  PREFIX:
    Type: String
    Description: Prefix for instance names

  SUBNETID:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for master EC2

  WORKERSUBNETS:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for worker Auto Scaling Group

  SECURITYGROUP:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for instances

  KEYNAME:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 key pair

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type

  WORKERINSTANCECOUNT:
    Type: Number
    Default: 2
    Description: Number of worker nodes

  LatestUbuntuAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id

Resources:

  ############################
  # IAM Managed Policies
  ############################

  CommonPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${PREFIX}-CommonPolicy"
      Description: Common CloudWatch permissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:*
              - logs:*
              - cloudwatch:PutMetricData
            Resource: "*"

  MasterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${PREFIX}-MasterPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: "*"

  WorkerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${PREFIX}-WorkerPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: "*"

  ############################
  # IAM Roles
  ############################

  MasterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Ref CommonPolicy
        - !Ref MasterPolicy

  WorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Ref CommonPolicy
        - !Ref WorkerPolicy

  ############################
  # Instance Profiles
  ############################

  MasterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MasterRole

  WorkerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WorkerRole

  ############################
  # Master EC2 Instance
  ############################

  MasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SUBNETID
      SecurityGroupIds:
        - !Ref SECURITYGROUP
      KeyName: !Ref KEYNAME
      ImageId: !Ref LatestUbuntuAMI
      IamInstanceProfile: !Ref MasterInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub "${PREFIX}-master"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt-get update -y
          apt-get install -y snapd wget jq
          snap install amazon-ssm-agent --classic
          systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
          systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service

          wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
          dpkg -i amazon-cloudwatch-agent.deb
          systemctl enable amazon-cloudwatch-agent
          systemctl start amazon-cloudwatch-agent

  ############################
  # Worker Launch Template
  ############################

  WorkerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${PREFIX}-WorkerLT"
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        ImageId: !Ref LatestUbuntuAMI
        KeyName: !Ref KEYNAME
        SecurityGroupIds:
          - !Ref SECURITYGROUP
        IamInstanceProfile:
          Name: !Ref WorkerInstanceProfile
        UserData:
          Fn::Base64: |
            #!/bin/bash
            apt-get update -y
            apt-get install -y snapd wget jq
            snap install amazon-ssm-agent --classic
            systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
            systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service

            wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
            dpkg -i amazon-cloudwatch-agent.deb
            systemctl enable amazon-cloudwatch-agent
            systemctl start amazon-cloudwatch-agent

  ############################
  # Worker Auto Scaling Group
  ############################

  WorkerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref WORKERSUBNETS
      LaunchTemplate:
        LaunchTemplateId: !Ref WorkerLaunchTemplate
        Version: !GetAtt WorkerLaunchTemplate.LatestVersionNumber
      MinSize: !Ref WORKERINSTANCECOUNT
      MaxSize: 5
      DesiredCapacity: !Ref WORKERINSTANCECOUNT
      Tags:
        - Key: Name
          Value: !Sub "${PREFIX}-worker"
          PropagateAtLaunch: true
